# Generated by Django 5.1.1 on 2024-12-02 14:23

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=255, validators=[events.models.validate_address], verbose_name='Адрес')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('marker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djeym.placemark')),
            ],
            options={
                'verbose_name': 'Сообщение о проблеме',
                'verbose_name_plural': 'Сообщения о проблемах',
            },
        ),
    ]
