# Generated by Django 5.1.1 on 2024-12-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_latitude_event_longitude_alter_event_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='marker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djeym.placemark'),
        ),
    ]
