# Generated by Django 5.1.3 on 2024-11-29 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('1', 'Погода'), ('2', 'Качество воздуха'), ('3', 'Уровень радиации')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
